services:
  db-products:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db-products
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Products123*
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'Products123*' -C -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 10

  product-service:
    build: 
      context: ./backend_infrastructure/product_service
      dockerfile: Dockerfile
    container_name: product_service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db-products;Database=db_products;User Id=sa;Password=Products123*;TrustServerCertificate=True
    ports:
      - "8081:8080"
    volumes:
      - ./backend_infrastructure/product_service:/app
      - /app/product_service/bin
      - /app/product_service/obj
    depends_on:
      db-products:
        condition: service_healthy

  db-transactions:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db-transactions
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Transactions123*
    ports:
      - "1434:1433" # Puerto diferente para no chocar con la otra DB
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'Transactions123*' -C -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5

  transaction-service:
    build: 
      context: ./backend_infrastructure/transaction_service
      dockerfile: Dockerfile
    container_name: transaction_service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db-transactions;Database=db_transactions;User Id=sa;Password=Transactions123*;TrustServerCertificate=True
    ports:
      - "8082:8080"
    volumes:
      - ./backend_infrastructure/transaction_service:/app
      - /app/transaction_service/bin
      - /app/transaction_service/obj
      - /app/transaction_service.data/bin
      - /app/transaction_service.data/obj
    depends_on:
      db-transactions:
        condition: service_healthy

  store-frontend:
    build:
      context: ./frontend_infrastructure/store_frontend
      dockerfile: Dockerfile
    container_name: store_frontend
    ports:
      - "4200:80"
    depends_on:
      - product-service
      - transaction-service