services:
  db-products:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db-products
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Products123*
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'Products123*' -C -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 10
  db-transactions:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db-transactions
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Transactions123*
      - MSSQL_PID=Developer
    ports:
      - "1434:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'Transactions123*' -C -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 10
  product-api:
    build: 
      context: ./backend_infrastructure/product_service
      dockerfile: Dockerfile
    container_name: product-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=db-products;Database=db_products;User Id=sa;Password=Products123*;TrustServerCertificate=True
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    ports:
      - "8081:8080"
    volumes:
      - ./backend_infrastructure/product_service:/app
    depends_on:
      db-products:
        condition: service_healthy
  transaction-api:
    build: 
      context: ./backend_infrastructure/transaction_service
      dockerfile: Dockerfile
    container_name: transaction-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=db-transactions;Database=db_transactions;User Id=sa;Password=Transactions123*;TrustServerCertificate=True
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    ports:
      - "8082:8080"
    volumes:
      - ./backend_infrastructure/transaction_service:/app
    depends_on:
      db-transactions:
        condition: service_healthy
  frontend:
    build: 
      context: ./frontend_infrastructure
      dockerfile: Dockerfile
    container_name: angular-frontend
    ports:
      - "4200:80"